# Generated by Django 2.0.3 on 2018-05-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.TextField(default=None, verbose_name='Exercises'),
            preserve_default=False,
        ),
    ]
