# Generated by Django 2.0.3 on 2018-05-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.TextField(default=None, verbose_name='Exercises'),
        ),
    ]
