# Generated by Django 2.0.3 on 2018-05-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_remove_workout_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='primary_muscle_group',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='secondary1_muscle_group',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='primary',
            field=models.TextField(verbose_name='Primary Exercises'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='secondary',
            field=models.TextField(verbose_name='Secondary Exercises'),
        ),
    ]
