# Generated by Django 2.0.3 on 2018-05-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20180504_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='secondary1_muscle_group',
            new_name='secondary_muscle_group',
        ),
    ]
