# Generated by Django 2.0.3 on 2018-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_auto_20180504_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.TextField(default=None),
        ),
    ]
