# Generated by Django 2.0.3 on 2018-05-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_auto_20180508_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='End time of Workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Start time of Workout'),
        ),
    ]
