# Generated by Django 2.0.3 on 2018-05-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0017_auto_20180510_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Back', 'Back'), ('Chest', 'Chest')], max_length=200),
        ),
    ]
