# Generated by Django 2.0.3 on 2018-05-26 20:03

from django.db import migrations, models


def make_muscle_group_uppercase(apps, schema_editor):
    Exercise = apps.get_model("workout", "Exercise")

    for e in Exercise.objects.all():
        e.muscle_group = e.muscle_group.upper()
        e.save()


def capitalize_muscle_group(apps, schema_editor):
    Exercise = apps.get_model("workout", "Exercise")

    for e in Exercise.objects.all():
        e.muscle_group = e.muscle_group.capitalize()
        e.save()


class Migration(migrations.Migration):
    dependencies = [
        ('workout', '0017_auto_20180510_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(
                choices=[('ARMS', 'Arms'), ('SHOULDERS', 'Shoulders'), ('LEGS', 'Legs'), ('BACK', 'Back'),
                         ('CHEST', 'Chest')], max_length=200),
        ),
        migrations.RunPython(make_muscle_group_uppercase, capitalize_muscle_group)
    ]
