# Generated by Django 2.0.3 on 2018-05-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0019_workoutdatacache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdatacache',
            name='workout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workout.Workout'),
        ),
    ]
