# Generated by Django 2.0.3 on 2018-05-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0020_auto_20180527_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdatacache',
            name='kcals',
            field=models.FloatField(blank=True, default=None, verbose_name='KCALs Burned from Workout'),
        ),
    ]
