# Generated by Django 2.0.3 on 2018-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0021_auto_20180527_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdatacache',
            name='kcals',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='KCALs Burned from Workout'),
        ),
    ]
