# Generated by Django 2.0.3 on 2018-05-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0023_exerciseset_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseset',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['id']},
        ),
    ]
