# Generated by Django 2.0.3 on 2018-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Weight'),
        ),
    ]
